Build against EAP 1
For some reason EAP 2 causes a cryptic exception when compiling
 the gradle tooling extension:
 jdk.internal.util.jar.InvalidJarIndexError: Invalid index